"use client";
import { useEffect, useState } from "react";
type Note = { id: string; name: string; frame: string; engine: string; wheels: string; observation: string };
const KEY = "create-a-car-notebook-v1";
const empty = { name: "", frame: "", engine: "", wheels: "", observation: "" };
const valid = (n: unknown): n is Note => !!n && typeof n === "object" && ["id", "name", "frame", "engine", "wheels", "observation"].every(k => typeof (n as Record<string, unknown>)[k] === "string");
export default function Notebook() {
 const [notes,setNotes] = useState<Note[]>([]), [form,setForm] = useState(empty), [status,setStatus] = useState(""), [ready,setReady] = useState(false), [canSave,setCanSave] = useState(true);
 useEffect(() => { try {const saved=localStorage.getItem(KEY);if(saved){const parsed:unknown=JSON.parse(saved);if(!Array.isArray(parsed)||!parsed.every(valid))throw new Error("invalid");setNotes(parsed);}}catch{setStatus("Saved notes could not be read. Existing storage has not been changed. New notes will stay in this tab only.");setCanSave(false);}finally{setReady(true);}},[]);
 function persist(next:Note[]){setNotes(next);if(!canSave){setStatus("Saved in this tab only. Export notes before closing it.");return;}try{localStorage.setItem(KEY,JSON.stringify(next));setStatus("Saved in this browser.");}catch{setStatus("Browser storage is unavailable. Notes remain in this tab; export them before closing it.");}}
 function submit(e:React.FormEvent){e.preventDefault();if(!form.name.trim()||!form.observation.trim()){setStatus("Add a build name and an observation before saving.");return;}persist([...notes,{...Object.fromEntries(Object.entries(form).map(([k,v])=>[k,v.trim()])) as typeof empty,id:crypto.randomUUID()}]);setForm(empty);}
 function download(){try{const blob=new Blob([JSON.stringify({format:"create-a-car-notebook-v1",notes},null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="create-a-car-notes.json";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus("Export prepared. Check your browser downloads.");}catch{setStatus("The download could not be created. Select and copy your visible notes instead.");}}
 return <><form onSubmit={submit} noValidate className="card"><h2>Record a build</h2><div className="fields">{([ ["name","Build name"],["frame","Frame"],["engine","Engine"],["wheels","Wheels"]] as const).map(([key,label])=><label key={key}>{label}{key==="name"?" (required)":" (optional)"}<input value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} maxLength={120} /></label>)}<label className="wide">What changed or happened? (required)<textarea value={form.observation} onChange={e=>setForm({...form,observation:e.target.value})} maxLength={2000} placeholder="Record only what you observed: the change, conditions, and result." /></label></div><div className="actions"><button className="button primary" disabled={!ready} type="submit">Save note</button><button className="button" type="button" onClick={()=>{setForm(empty);setStatus("Form cleared. Saved notes kept.");}}>Clear form</button></div></form><p role="status" className="status">{ready?status:"Loading saved notes…"}</p><div className="section"><h2>Your saved observations</h2><p className="muted">These are your notes. This site does not score builds, predict earnings, or read your Roblox inventory.</p>{!notes.length?<p className="note">No saved notes yet. Add one above, then record another setup to compare your observations.</p>:<div className="notes">{notes.map(n=><article className="card" key={n.id}><h3>{n.name}</h3><dl><dt>Frame</dt><dd>{n.frame||"Not recorded"}</dd><dt>Engine</dt><dd>{n.engine||"Not recorded"}</dd><dt>Wheels</dt><dd>{n.wheels||"Not recorded"}</dd></dl><p>{n.observation}</p><button className="button" onClick={()=>persist(notes.filter(item=>item.id!==n.id))} aria-label={"Delete "+n.name}>Delete note</button></article>)}</div>}<button className="button" disabled={!notes.length} onClick={download}>Export notes</button></div></>;
}
