import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const root='D:/AI建站',{chromium}=createRequire(root+'/worm-capitalist-wiki/package.json')('@playwright/test');const browser=await chromium.launch({channel:'chrome',headless:true});
try{for(const site of ['create-a-car-wiki','win-a-world-championship-wiki']){
 const project=path.join(root,site),out=path.join(project,'out'),report={checkedAt:new Date().toISOString(),scope:'Actual local Chrome request and metadata checks for existing SVG favicon',pages:[],networkErrors:[],consoleErrors:[]};
 const server=http.createServer((req,res)=>{let f=path.resolve(out,'.'+new URL(req.url,'http://localhost').pathname);if(f!==out&&!f.startsWith(out+path.sep)){res.writeHead(403);return res.end();}if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');if(!fs.existsSync(f)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml'})[path.extname(f)]||'application/octet-stream');fs.createReadStream(f).pipe(res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const origin='http://127.0.0.1:'+server.address().port,page=await browser.newPage();page.on('pageerror',e=>report.consoleErrors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.consoleErrors.push(m.text())});page.on('response',r=>{if(r.status()>=400)report.networkErrors.push({url:r.url(),status:r.status()})});
 try{for(const route of JSON.parse(fs.readFileSync(path.join(project,'quality/artifacts/routes.json')))){
  await page.goto(origin+route,{waitUntil:'networkidle'});const icon=await page.locator('link[rel="icon"]').getAttribute('href');assert.equal(icon,'/favicon.svg');const result=await page.evaluate(async href=>{const r=await fetch(href);return {status:r.status,contentType:r.headers.get('content-type'),text:await r.text()}},icon);assert.equal(result.status,200);assert.match(result.text,/<svg\b/);report.pages.push({path:route,href:icon,status:result.status,contentType:result.contentType});
 }}finally{await page.close();await new Promise(r=>server.close(r));}
 assert.deepEqual(report.networkErrors,[]);assert.deepEqual(report.consoleErrors,[]);report.passed=true;fs.writeFileSync(path.join(project,'quality/clean-git-gate/favicon-check.json'),JSON.stringify(report,null,2));console.log(site,report.pages.length,'favicon routes pass');
}}finally{await browser.close();}
